DELETE FROM Processes WHERE Type = 'PROCESS_WEALTH';
DELETE FROM Processes WHERE Type = 'PROCESS_RESEARCH';

UPDATE Leader_Flavors 
SET Flavor=1 
WHERE FlavorType='FLAVOR_AIR_CARRIER';

DELETE FROM Buildings WHERE Type='BUILDING_FW_BuenosAiresForumCT';
DELETE FROM Buildings WHERE Type='BUILDING_FW_PHOLUS_MUTAGEN';
